### ISSUE TITLE
not work even after reinstalling the extension (Tampermonkey) and this script.

### ISSUE THREAD

**Issue by shenwei356** [VitoVan/Weibored.js#4]
Hi,

Thanks for this practical script. It worked well few months ago, and I disable the script after using it.

Today I enabled the extension and script again, and even reinstall them following your guide. However, it still failed to start.

Any help is appreciated.

**Comment by VitoVan** [comment]
Thank you very much for reporting this!!! :heart: 

It may because of this PR: https://github.com/VitoVan/Weibored.js/pull/3
I merged it without checking, it's my fault.

Now I have reverted it, and synced with greasyfork, you can now try delete the script and reinstall it now.

I hope this will work.

**Comment by shenwei356** [comment]
It works now! Thank you.

**Comment by VitoVan** [comment]
@shenwei356 My pleasure :smile_cat:
